[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = ["npm install"]

[phases.build]
cmds = [
  "npm run build --workspace=@credpriv/shared",
  "npm run db:generate --workspace=@credpriv/backend",
  "npm run build --workspace=@credpriv/backend"
]

[start]
cmd = "cd backend && npx prisma migrate deploy && npm start"
